
(function(){
  const ANGELI = [
    {id:1,free:true,nome:'Michele',emoji:'⚔️',grado:'Arcangelo — Principe delle Milizie Celesti',
    html:`<h4>📖 Chi è</h4><p>Michele è il più potente degli arcangeli, comandante dell'esercito celeste. Il suo nome significa <em>"Chi è come Dio?"</em> — una sfida diretta a Satana. È raffigurato con spada fiammeggiante e armatura d'oro.</p><h4>🌟 Attributi</h4><p>Forza, giustizia, protezione, coraggio. Governa il pianeta Sole e il giorno domenicale. Il suo colore è il blu reale e il dorato.</p><h4>🔮 Curiosità</h4><p>In quasi tutte le tradizioni monoteiste Michele è citato: nella Bibbia, nel Corano come Mīkāl, nella Cabala come capo della Sephira Hesed. Si dice che abbia combattuto Satana durante la caduta degli angeli ribelli.</p><h4>📜 Storie</h4><p>Secondo il Libro di Daniele, Michele è il protettore d'Israele. Nella tradizione cristiana medievale pesava le anime dei defunti durante il Giudizio. Giovanna d'Arco affermava di sentire la sua voce che la guidava in battaglia.</p>`},
    {id:2,free:false,nome:'Gabriele',emoji:'📯',grado:'Arcangelo — Messaggero di Dio',
    html:`<h4>📖 Chi è</h4><p>Gabriele è il messaggero per eccellenza del divino. Il suo nome significa <em>"Forza di Dio"</em>. Annunciò la nascita di Giovanni Battista e l'Incarnazione a Maria. Nel Corano è Jibrīl, colui che rivelò il testo sacro a Maometto.</p><h4>🌟 Attributi</h4><p>Comunicazione, rivelazione, intuizione, arte. Governa la Luna e il lunedì. I suoi colori sono il bianco e l'argento.</p><h4>🔮 Curiosità</h4><p>Nella Cabala Gabriele presiede alla Sephira Yesod, legata ai sogni e all'inconscio. Nell'esoterismo islamico è considerato il Sanctus Spiritus, il soffio vitale dell'universo.</p><h4>📜 Storie</h4><p>William Blake lo dipinse come una figura androgina avvolta di luce lunare. Nella tradizione etiope, Gabriele è patrono delle donne incinte e gli viene dedicata una festa mensile.</p>`},
    {id:3,free:false,nome:'Raffaele',emoji:'🌿',grado:'Arcangelo — Angelo della Guarigione',
    html:`<h4>📖 Chi è</h4><p>Raffaele — <em>"Dio guarisce"</em> — è l'arcangelo della salute, del viaggio e della scienza medica. È protagonista del Libro di Tobia, dove guarisce la cecità del vecchio Tobi e accompagna il figlio nel lungo pellegrinaggio.</p><h4>🌟 Attributi</h4><p>Guarigione, viaggi, scienza, medicina. Governa Mercurio e il mercoledì. Il suo colore è il verde smeraldo e il giallo dorato.</p><h4>🔮 Curiosità</h4><p>La tradizione lo vuole guardiano del paradiso terrestre. È patrono dei farmacisti, dei medici e dei viaggiatori. Nel Libro di Enoch è uno dei quattro angeli che sorvegliano i punti cardinali.</p><h4>📜 Storie</h4><p>Nell'alchimia medievale era invocato durante le operazioni di sublimazione. Bandì Asmodeo in Egitto mediante il fumo di fegato di pesce, uno dei rituali più bizzarri della letteratura angelica.</p>`},
    {id:4,free:false,nome:'Uriel',emoji:'🕯️',grado:'Arcangelo — Fuoco di Dio',
    html:`<h4>📖 Chi è</h4><p>Uriel, <em>"Fuoco di Dio"</em> o "Luce di Dio", è l'arcangelo della saggezza e dell'illuminazione interiore. Nella tradizione ebraica vigilò con spada fiammeggiante sull'Eden dopo la cacciata di Adamo.</p><h4>🌟 Attributi</h4><p>Saggezza, profezia, scienza occulta, luce interiore. Governa il Nord e la Terra. Il suo colore è il rosso rubino e l'ambra.</p><h4>🔮 Curiosità</h4><p>Uriel fu rimosso dal canone cattolico nel Concilio di Roma del 745 d.C. Rimane centrale nella tradizione esoterica, nella Cabala e nell'angeleologia etiope.</p><h4>📜 Storie</h4><p>Il Libro di Enoch descrive Uriel come colui che mostrò ai profeti i segreti del calendario cosmico. John Milton nel Paradiso Perduto lo chiama "il più acuto degli angeli" e lo colloca come guardiano del Sole.</p>`},
    {id:5,free:false,nome:'Azrael',emoji:'🖤',grado:'Angelo della Morte',
    html:`<h4>📖 Chi è</h4><p>Azrael, l'Angelo della Morte nell'Islam e nella tradizione ebraica, separa l'anima dal corpo al momento della morte. Non è il "falciatore" della tradizione popolare, ma un accompagnatore misericordioso nel passaggio.</p><h4>🌟 Attributi</h4><p>Transizione, commiato, pace dei defunti. Governa Saturno e il sabato. I suoi colori sono il nero e il viola scuro.</p><h4>🔮 Curiosità</h4><p>Secondo la leggenda islamica il suo corpo è così grande da abbracciare l'universo intero. Ogni volta che muore qualcuno nel mondo, un foglio cade dal suo albero cosmico che conta le vite di ogni essere.</p><h4>📜 Storie</h4><p>Una storia sufi narra di un uomo che, incontrato Azrael al mercato, fuggì a Samarcanda. Azrael disse a Salomone: "Ero sorpreso di vederlo a Baghdad, avevo un appuntamento con lui domani a Samarcanda."</p>`},
    {id:6,free:false,nome:'Metatron',emoji:'👁️',grado:'Angelo del Trono — Il Re degli Angeli',
    html:`<h4>📖 Chi è</h4><p>Metatron è considerato il più alto degli angeli nella mistica ebraica. Secondo alcune tradizioni è il profeta Enoch trasformato in essere celeste dopo essere salito al cielo in vita.</p><h4>🌟 Attributi</h4><p>Scrittura sacra, record akashici, volontà divina. Il suo sigillo è il Cubo di Metatron, figura geometrica sacra contenente tutti i solidi platonici.</p><h4>🔮 Curiosità</h4><p>Nella Cabala presiede alla Sephira Keter, la corona, il punto più alto dell'Albero della Vita. È lo scriba celeste che registra ogni azione umana e custodisce i misteri dell'universo.</p><h4>📜 Storie</h4><p>Il Talmud narra che quando un rabbino vide Metatron seduto come se fosse Dio, credette ci fossero due potenze celesti. Per questo Metatron ricevette 60 colpi di fuoco — episodio unico nella letteratura angelica.</p>`},
    {id:7,free:false,nome:'Sandalfon',emoji:'🌲',grado:'Angelo della Preghiera — Fratello Gemello di Metatron',
    html:`<h4>📖 Chi è</h4><p>Sandalfon è identificato con il profeta Elia, asceso al cielo senza morire. È il gemello di Metatron e il suo nome in greco significa "co-fratello". La Cabala lo pone alla Sephira Malkuth, il regno terrestre, il polo opposto di Metatron.</p><h4>🌟 Attributi</h4><p>Preghiera, musica, trasmissione dei desideri al divino. È talmente alto che persino Michele teme la sua statura. Governa la Terra e la manifestazione materiale.</p><h4>🔮 Curiosità</h4><p>Longfellow gli dedicò un'intera poesia, "Sandalphon", dove lo descrive nell'atto di raccogliere tutte le preghiere dell'umanità e intrecciarle in una ghirlanda per portarle a Dio.</p><h4>📜 Storie</h4><p>Secondo la mistica ebraica, Sandalfon è così alto che ci vogliono 500 anni per percorrere la distanza tra i suoi piedi e la sua testa. Trasforma le preghiere in corone di fiori per la testa del Creatore.</p>`},
    {id:8,free:false,nome:'Samael',emoji:'🐍',grado:'Angelo del Veleno — Principe della Giustizia Divina',
    html:`<h4>📖 Chi è</h4><p>Samael è una delle figure più ambigue della angelologia ebraica. Il suo nome significa "Veleno di Dio" o "Angelo di Dio". È contemporaneamente il grande accusatore, l'Angelo della Morte, e il principe di Roma nella mistica rabbinica.</p><h4>🌟 Attributi</h4><p>Prova, castigo, giustizia severa. È identificato con il serpente del Paradiso. Nella Cabala governa Geburah, la Sephira della severità e della forza.</p><h4>🔮 Curiosità</h4><p>A differenza di Satana, che nella Bibbia ebraica è una funzione (l'avversario), Samael è un essere con una propria personalità. Nella tradizione mistica è il marito di Lilith e padre di demoni.</p><h4>📜 Storie</h4><p>Il Midrash narra che Samael scese dal cielo per tentare Adamo ed Eva in forma di serpente. Combatté con Giacobbe lungo il guado del fiume Yabbok — l'episodio in cui il patriarca lottò tutta la notte con un "uomo" e ottenne la benedizione.</p>`},
    {id:9,free:false,nome:'Chamuel',emoji:'💗',grado:'Arcangelo dell\'Amore e delle Relazioni',
    html:`<h4>📖 Chi è</h4><p>Chamuel, il cui nome significa "Colui che vede Dio" o "Chi cerca Dio", è l'arcangelo dell'amore compassionevole. Non è citato nelle Scritture canoniche ma è centrale nella tradizione esoterica cristiana e nella New Age.</p><h4>🌟 Attributi</h4><p>Amore incondizionato, relazioni, pace interiore, riconciliazione. Il suo colore è il rosa pallido. È invocato per ritrovare oggetti perduti, relazioni in crisi e autostima.</p><h4>🔮 Curiosità</h4><p>Alcune tradizioni lo identificano con l'angelo che confortò Gesù nel Getsemani prima della Passione. È patrono dell'amore romantico ma anche dell'amor proprio, spesso trascurato nella spiritualità tradizionale.</p><h4>📜 Storie</h4><p>Nella teosofia ottocentesca di Helena Blavatsky e poi in Alice Bailey, Chamuel è uno dei Sette Raggi, ciascuno governato da un Elohim o Arcangelo. Il suo Raggio Rosa è il raggio dell'amore attivo nel mondo.</p>`},
    {id:10,free:false,nome:'Jofiel',emoji:'🌸',grado:'Arcangelo della Bellezza e della Saggezza',
    html:`<h4>📖 Chi è</h4><p>Jofiel, "Bellezza di Dio", è l'arcangelo dell'illuminazione intellettuale e della bellezza in tutte le sue forme. Alcune tradizioni lo identificano con il cherubino che custodì l'Eden con la spada fiammeggiante dopo la caduta.</p><h4>🌟 Attributi</h4><p>Arte, bellezza, saggezza, creatività, comprensione profonda. Il suo colore è il giallo brillante o il rosa dorato. È l'angelo da invocare durante lo studio e la creazione artistica.</p><h4>🔮 Curiosità</h4><p>Nel Libro di Enoch, Jofiel è menzionato come uno dei principi celesti che governano il sapere. La tradizione esoterica lo vuole custode dell'Albero della Conoscenza, da non confondere con la Conoscenza del Bene e del Male.</p><h4>📜 Storie</h4><p>In alcune tradizioni cabalistiche, Jofiel era il tutore dei figli di Noè e istruì Sem nella trasmissione della sapienza primordiale. È patrono degli artisti, degli scrittori e di chiunque cerchi di incarnare il divino nella materia.</p>`},
    {id:11,free:false,nome:'Haniel',emoji:'🌙',grado:'Angelo della Luna e delle Virtù',
    html:`<h4>📖 Chi è</h4><p>Haniel, "Grazia di Dio" o "Gloria di Dio", governa il pianeta Venere e la Luna nella tradizione esoterica. È l'arcangelo dei cicli lunari, dell'intuizione femminile e delle energie naturali stagionali.</p><h4>🌟 Attributi</h4><p>Intuizione, cicli lunari, magia naturale, grazia. Il suo colore è il blu-verde lunare o il turchese. È l'angelo da invocare durante le fasi di luna piena e nei rituali di guarigione emotiva.</p><h4>🔮 Curiosità</h4><p>Nella tradizione cabbalistica Haniel governa la Sephira Netzach, legata alle emozioni, alla natura e alla creatività erotica. È uno dei principi angelici dell'Ordine delle Virtù.</p><h4>📜 Storie</h4><p>La leggenda vuole che Haniel avesse accompagnato il profeta Enoch durante la sua ascesa al cielo, guidandolo tra le sfere celesti. Il suo nome veniva scritto sugli amuleti delle donne in gravidanza nel Medio Oriente medievale.</p>`},
    {id:12,free:false,nome:'Azael',emoji:'🌪️',grado:'Angelo Vigilante — Custode dei Segreti Celesti',
    html:`<h4>📖 Chi è</h4><p>Azael (da non confondere con Azazel) è uno degli angeli Vigilanti del Libro di Enoch, coloro che discesero sulla Terra e si unirono alle figlie degli uomini. Il suo nome significa "Dio si è reso forte".</p><h4>🌟 Attributi</h4><p>Segreti cosmici, magia proibita, conoscenza delle erbe e degli incantesimi. Fu uno dei principali Vigilanti che trasmisero all'umanità conoscenze che il cielo aveva riservato agli angeli.</p><h4>🔮 Curiosità</h4><p>Il Libro di Enoch distingue accuratamente Azael da Azazel, sebbene i due nomi vengano spesso confusi. I Vigilanti, detti Benei Elohim ("figli di Dio"), sono il soggetto di una delle tradizioni più enigmatiche di tutta la letteratura apocalittica.</p><h4>📜 Storie</h4><p>Secondo Enoch, gli angeli Vigilanti insegnarono alle donne l'arte del trucco e ai guerrieri la forgiatura delle armi. Per questo crimine furono incatenati nelle profondità della terra fino al Giudizio Finale.</p>`},
    {id:13,free:false,nome:'Raziel',emoji:'📚',grado:'Angelo dei Misteri — Custode dei Segreti Divini',
    html:`<h4>📖 Chi è</h4><p>Raziel, "Segreto di Dio", è l'angelo che custodisce la conoscenza di tutti i misteri dell'universo. Si dice che abbia donato ad Adamo un libro — il Sefer Raziel HaMalakh — contenente i segreti della creazione.</p><h4>🌟 Attributi</h4><p>Conoscenza occulta, alchimia, scienza sacra, magia cerimoniale. È il principe dell'Ordine dei Cherubini e sta ai piedi del Trono divino ad ascoltare e registrare tutto.</p><h4>🔮 Curiosità</h4><p>Il Sefer Raziel è un vero testo kabbalistico medievale, ancora pubblicato oggi. Contiene angeli, nomi divini, astrologia, amuleti e rituali. Si dice che chi lo possiede nella propria casa è protetto dagli incendi.</p><h4>📜 Storie</h4><p>Secondo il Midrash, dopo che Raziel donò il libro ad Adamo, gli angeli lo gettarono nell'oceano per gelosia. Dio ordinò a Rahab, principe del mare, di recuperarlo e restituirlo. In seguito il libro passò ad Enoch, poi a Noè, poi a Salomone.</p>`},
    {id:14,free:false,nome:'Zadkiel',emoji:'💜',grado:'Arcangelo della Misericordia e del Perdono',
    html:`<h4>📖 Chi è</h4><p>Zadkiel, "Giustizia di Dio", è l'arcangelo della misericordia, del perdono e della trasformazione. Nella tradizione ebraica è identificato con l'angelo che fermò la mano di Abramo nell'atto di sacrificare Isacco.</p><h4>🌟 Attributi</h4><p>Perdono, compassione, trasformazione positiva, memoria. Il suo colore è il viola profondo. Governa Giove nella tradizione astrologica esoterica.</p><h4>🔮 Curiosità</h4><p>Nella teosofia e nella tradizione dei "Chierici Violet Flame", Zadkiel è associato alla Fiamma Viola, energia trasmutatrice capace di purificare il karma. La sua invocazione è centrale nella pratica dei cercatori spirituali moderni.</p><h4>📜 Storie</h4><p>Il Zohar, il testo fondamentale della Cabala, descrive Zadkiel come uno dei sette arcangeli che circondano il Trono. È il patrono di chi chiede perdono e di chi deve concederlo — entrambe le operazioni spirituali più difficili per l'essere umano.</p>`},
    {id:15,free:false,nome:'Baraquiel',emoji:'⚡',grado:'Angelo del Fulmine — Principe delle Stelle',
    html:`<h4>📖 Chi è</h4><p>Baraquiel, "Fulmine di Dio", è uno degli arcangeli menzionati nel Libro di Enoch. Governa i fenomeni atmosferici e in particolare i fulmini. Il suo nome appare anche come Barachiel o Barakiel.</p><h4>🌟 Attributi</h4><p>Fortuna, benedizione, stelle e fenomeni celesti. Nella tradizione cristiana orientale è considerato patrono della fortuna e dell'abbondanza. I suoi simboli sono il fulmine e il rosa bianco.</p><h4>🔮 Curiosità</h4><p>Nel Libro di Enoch, Baraquiel è uno dei secondi capi dei Vigilanti. La Chiesa ortodossa greca lo venera come arcangelo il 8 novembre, giorno in cui si commemora il Sinassi degli Angeli.</p><h4>📜 Storie</h4><p>Nella tradizione popolare greca, Baraquiel è invocato dai pescatori prima delle tempeste. Si narra che appaia come una luce bianca in mezzo ai lampi, portando con sé la promessa che la tempesta passerà senza vittime.</p>`},
    {id:16,free:false,nome:'Anael',emoji:'🌹',grado:'Angelo di Venere — Signore degli Amori',
    html:`<h4>📖 Chi è</h4><p>Anael (o Hanael, Aniel) è l'angelo che governa il pianeta Venere nella magia cerimoniale medievale. Appare nei grimori rinascimentali come signore del venerdì, giorno sacro a Venere, e presiede alle questioni d'amore e bellezza.</p><h4>🌟 Attributi</h4><p>Amore romantico, desiderio, arte, musica, fertilità. Il suo sigillo veniva inciso su lamine di rame (metallo di Venere) per i rituali amorosi. Governa il tramonto e le prime ore della notte.</p><h4>🔮 Curiosità</h4><p>Nel Clavicola di Salomone e nel Picatrix, Anael è invocato per ottenere favori in amore, per placare le liti tra amanti e per rendere una persona attraente agli occhi degli altri. La sua stella è quella della sera.</p><h4>📜 Storie</h4><p>Un grimorio del XVI secolo descrive Anael come un giovane bellissimo con una corona di rose, seduto su un leone dorato. La sua invocazione richiedeva incenso di sandalo e rose, candele verdi, e doveva essere compiuta il venerdì sera quando Venere era visibile all'orizzonte.</p>`},
    {id:17,free:false,nome:'Cassiel',emoji:'⏳',grado:'Angelo di Saturno — Custode del Tempo',
    html:`<h4>📖 Chi è</h4><p>Cassiel è l'angelo che governa il pianeta Saturno nella tradizione della magia planetaria medievale. Il suo nome significa "Velocità di Dio". È associato al tempo, alla solitudine, alle lacrime e alla contemplazione profonda.</p><h4>🌟 Attributi</h4><p>Tempo, karma, disciplina, solitudine feconda, saggezza degli anziani. Governa il sabato. I suoi colori sono il nero e il grigio piombo. È invocato per questioni di disciplina, studio e concentrazione.</p><h4>🔮 Curiosità</h4><p>Il Picatrix lo descrive come un vecchio con barba lunga, che regge una falce — immagine che si confonde con quella di Crono/Saturno. È il patrono degli eremiti, dei monaci e di coloro che scelgono la via della rinuncia.</p><h4>📜 Storie</h4><p>Nell'alchimia Cassiel presiede alla "nigredo", la fase oscura e decomposizione della materia prima. Era invocato dai filosofi durante la notte del sabato per ricevere visioni sulla natura del tempo e sull'eternità.</p>`},
    {id:18,free:false,nome:'Sachiel',emoji:'🌊',grado:'Angelo di Giove — Dispensatore di Ricchezza',
    html:`<h4>📖 Chi è</h4><p>Sachiel governa il pianeta Giove e il giovedì nella magia planetaria. Il suo nome significa "Copertura di Dio" o "Abbondanza di Dio". Presiede alla prosperità materiale, all'espansione e alla generosità.</p><h4>🌟 Attributi</h4><p>Abbondanza, successo, benessere, giustizia, onore. I suoi colori sono il blu reale e il viola. È invocato per questioni finanziarie, legali e per ottenere posizioni di potere.</p><h4>🔮 Curiosità</h4><p>Nel Clavicola di Salomone, Sachiel appare come un uomo maestoso con un bastone e un'aquila ai piedi. I rituali a lui dedicati si compivano con incenso di cedro e legno di quercia, entrambi simboli di regalità e longevità.</p><h4>📜 Storie</h4><p>Una leggenda medievale racconta che un mercante in rovina invocò Sachiel con i dovuti riti. Quella stessa notte trovò una mappa del tesoro in un sogno così vivido da sembrare reale. Il tesoro esisteva davvero, sepolto sotto la pavimentazione della sua bottega.</p>`},
    {id:19,free:false,nome:'Camael',emoji:'🔥',grado:'Angelo di Marte — Principe della Forza',
    html:`<h4>📖 Chi è</h4><p>Camael (o Camiel, Chamuel) è l'angelo che governa il pianeta Marte. Nella tradizione esoterica è il principe dell'ordine delle Potestà. Alcuni lo identificano con l'angelo che lottò con Giacobbe, altri con colui che apparve a Gesù nel Getsemani per confortarlo.</p><h4>🌟 Attributi</h4><p>Forza, coraggio, conflitto giusto, iniziazione attraverso la prova. Governa il martedì. Il suo colore è il rosso fuoco. È invocato da guerrieri, atleti e da chi affronta prove difficili.</p><h4>🔮 Curiosità</h4><p>Nella Cabala Camael presiede alla Sephira Geburah, la severità. È il bilanciamento necessario: senza forza e severità, la gentilezza diventa debolezza. Il suo nome appare inciso su amuleti protettivi ritrovati in scavi medievali.</p><h4>📜 Storie</h4><p>John Dee, il matematico e occultista elisabettiano, comunicò con Camael durante le sue sessioni di scrying con Edward Kelley. L'angelo avrebbe rivelato l'alfabeto enochiano, ancora oggi usato nella magia cerimoniale.</p>`},
    {id:20,free:false,nome:'Ariel',emoji:'🦁',grado:'Angelo della Natura — Signore degli Elementi',
    html:`<h4>📖 Chi è</h4><p>Ariel, "Leone di Dio", è l'angelo che presiede alla natura selvaggia, agli elementi e agli animali selvatici. Appare sia nelle tradizioni giudaiche che nei grimori rinascimentali come spirito della terra e dell'aria.</p><h4>🌟 Attributi</h4><p>Natura, elementi, animali, ecologia spirituale. Si manifesta spesso sotto forma di leone o aquila. I suoi colori sono il verde foresta e il dorato della savana.</p><h4>🔮 Curiosità</h4><p>Shakespeare lo usò come personaggio nella Tempesta, dove Ariel è uno spirito dell'aria al servizio del mago Prospero. Questa scelta non fu casuale: il nome era noto agli studiosi rinascimentali dell'occultismo.</p><h4>📜 Storie</h4><p>Nelle tradizioni degli sciamani europei medievali, Ariel era invocato prima di entrare nelle foreste per ricevere protezione dagli animali pericolosi e per comprendere il linguaggio della natura. Ancora oggi alcuni cercatori spirituali lo invocano per connettersi con gli spiriti della terra.</p>`},
  ];

  const DIAVOLI = [
    {id:1,free:true,nome:'Lucifero',emoji:'🌟',grado:'Portatore di Luce — Principe Caduto',
    html:`<h4>📖 Chi è</h4><p>Il nome Lucifero — <em>"Portatore di Luce"</em> — deriva dal latino e indicava la stella del mattino (Venere). Nella tradizione cristiana divenne il nome dell'angelo caduto per superbia, identificato con Satana. Per i Gnostici era invece un eroe che sfidò il demiurgo ignorante.</p><h4>🌟 Attributi</h4><p>Intelligenza suprema, bellezza devastante, orgoglio cosmico, conoscenza proibita. Nelle arti esoteriche rappresenta il principio dell'illuminazione attraverso la ribellione.</p><h4>🔮 Curiosità</h4><p>La poesia romantica ne ha fatto un simbolo di libertà e intelletto ribelle. Byron, Shelley e Baudelaire scrissero su di lui con ammirazione. Il filosofo Hegel lo citò come la dialettica stessa.</p><h4>📜 Storie</h4><p>John Milton nel Paradiso Perduto crea un Lucifero tragico: "Meglio regnare all'Inferno che servire in Paradiso." Dante lo colloca nel punto più basso dell'Inferno, incastrato nel ghiaccio, che batte le ali in eterno senza poter volare.</p>`},
    {id:2,free:false,nome:'Asmodeo',emoji:'👹',grado:'Re dei Demoni della Lussuria',
    html:`<h4>📖 Chi è</h4><p>Asmodeo è uno dei demoni più antichi e potenti, citato nel Libro di Tobia dove tormenta Sara uccidendo sette mariti nella notte di nozze. Il nome deriva dal persiano Aēšma-daēva, demone dell'ira e della bramosia.</p><h4>🌟 Attributi</h4><p>Lussuria, gelosia, gioco d'azzardo, vendetta amorosa. La Lemegeton lo descrive con tre teste (toro, uomo, ariete) e coda di serpente, che cavalca un drago sputafuoco. Comanda 72 legioni di demoni.</p><h4>🔮 Curiosità</h4><p>Aiutò Salomone nella costruzione del Tempio ma fu poi incatenato con l'Anello del Re. In Francia nel XVII secolo fu al centro del caso di possessione di Loudun.</p><h4>📜 Storie</h4><p>La leggenda talmudica narra che Asmodeo si spacciò per Salomone stesso, regnando al suo posto per tre anni mentre il vero re vagava mendicando per le strade di Gerusalemme — la più audace impostura demoniaca della storia.</p>`},
    {id:3,free:false,nome:'Belzebù',emoji:'🪰',grado:'Signore delle Mosche — Principe dell\'Inferno',
    html:`<h4>📖 Chi è</h4><p>Belzebù, letteralmente "Signore delle Mosche" (dall'ebraico Baal Zebub), era originariamente una divinità cananea degli insetti. La Bibbia lo cita come "principe dei demoni". Nell'Inferno di Dante è il nome stesso di Satana.</p><h4>🌟 Attributi</h4><p>Superbia, gola, corruzione delle cose sacre. Spesso dipinto come mosca gigantesca o uomo obeso e putrescente. Secondo la Lemegeton comanda 66 legioni di demoni.</p><h4>🔮 Curiosità</h4><p>Nel Medioevo fu considerato il secondo nella gerarchia infernale. Il caso di possessione di Loudun nel 1634 vide Belzebù accusato insieme ad Asmodeo e Leviatano di aver corrotto un intero convento di suore.</p><h4>📜 Storie</h4><p>William Golding intitolò "Il Signore delle Mosche" il suo romanzo sulla corruzione dell'innocenza infantile. La scelta non fu casuale: Belzebù rappresenta esattamente quel momento in cui la civiltà crolla e la bestia emerge dall'interno.</p>`},
    {id:4,free:false,nome:'Lilith',emoji:'🦇',grado:'Regina dei Demoni — Prima Donna',
    html:`<h4>📖 Chi è</h4><p>Lilith è la figura femminile demoniaca della mitologia ebraica. Secondo il Midrash fu la prima moglie di Adamo, creata dalla polvere insieme a lui. Rifiutandosi di sottomettersi, abbandonò il Paradiso e divenne regina dei demoni.</p><h4>🌟 Attributi</h4><p>Indipendenza, sessualità selvaggia, maternità oscura. Consorte di Samael e regina degli spiriti notturni. Nella tradizione popolare rapisce i bambini nella notte.</p><h4>🔮 Curiosità</h4><p>Il suo nome potrebbe derivare dall'ebraico "lilit" (notte) o dall'accadico "lilitu" (spirito del vento). Nel femminismo contemporaneo è stata reinterpretata come simbolo di emancipazione. Carl Jung la usò come archetipo dell'ombra femminile.</p><h4>📜 Storie</h4><p>Gli amuleti "shir ha-maalot" erano affissi nelle stanze dei neonati per proteggerli da Lilith. In astrologia moderna il "Lilith Nera" è un punto lunare che rappresenta l'energia selvaggia repressa in ognuno di noi.</p>`},
    {id:5,free:false,nome:'Azazel',emoji:'🐐',grado:'Il Capro Espiatorio — Angelo Caduto',
    html:`<h4>📖 Chi è</h4><p>Azazel compare nel Levitico come entità a cui veniva consacrato il "capro espiatorio" nel Giorno dell'Espiazione. Nel Libro di Enoch è uno degli angeli Vigilanti caduti che insegnò all'umanità l'arte della guerra e il trucco femminile.</p><h4>🌟 Attributi</h4><p>Conoscenza proibita, tecnologia della guerra, seduzione. È legato al deserto e al capro. Secondo Enoch fu incatenato in un deserto buio fino al Giorno del Giudizio.</p><h4>🔮 Curiosità</h4><p>Il termine "capro espiatorio" nasce proprio da questo rito biblico. I Yezidi del Kurdistan veneravano Melek Taus (Angelo Pavone) identificato da alcuni con Azazel, causando secoli di incomprensioni e persecuzioni.</p><h4>📜 Storie</h4><p>In Enoch, Azazel viene incolpato di aver corrotto l'umanità più di qualsiasi altro Vigilante. "Tutto il peccato della terra è colpa tua" gli disse Dio prima di incatenarlo. Il suo insegnamento principale: forgiare spade e scudi. Il secondo: belletti e ornamenti per le donne.</p>`},
    {id:6,free:false,nome:'Mefistofele',emoji:'🎭',grado:'Il Tentatore — Demone del Dubbio',
    html:`<h4>📖 Chi è</h4><p>Mefistofele è il demone del contratto faustiano. Il nome ha origine incerta, probabilmente tedesco medievale. Non appare nei grimori ma nelle opere letterarie: il Faust di Marlowe e di Goethe lo rese immortale come tentatore raffinato e ironico.</p><h4>🌟 Attributi</h4><p>Ingegno diabolico, ironia, seduzione intellettuale, nichilismo. Non è violento ma sottile: convince attraverso la logica, il dubbio, il piacere.</p><h4>🔮 Curiosità</h4><p>Nel Faust di Goethe si definisce: "Parte di quella forza che sempre vuole il male e sempre compie il bene." È il perfetto antagonista dialettico che stimola la ricerca pur portando all'autodistruzione.</p><h4>📜 Storie</h4><p>La storia si basa su Johann Georg Faust, alchimista tedesco del XVI secolo. Il "Faustbuch" del 1587 creò il template del patto col diavolo, da cui attinsero Marlowe, Goethe, Berlioz, Thomas Mann e molti altri.</p>`},
    {id:7,free:false,nome:'Leviatano',emoji:'🌊',grado:'Bestia dell\'Abisso — Drago delle Profondità',
    html:`<h4>📖 Chi è</h4><p>Leviatano è il mostro marino primordiale della Bibbia, creatura del caos che Dio sconfisse all'alba del tempo. Nel Libro di Giobbe Dio lo usa per mostrare la propria onnipotenza. Nella demonologia medievale divenne uno dei principi dell'Inferno.</p><h4>🌟 Attributi</h4><p>Eresia, invidia, acque primordiali, caos. Peter Binsfeld nel 1589 lo associò al peccato capitale dell'invidia. È raffigurato come drago marino o serpente immenso che avvolge il mondo.</p><h4>🔮 Curiosità</h4><p>Thomas Hobbes intitolò il suo trattato di filosofia politica "Leviatano" (1651), usando il mostro biblico come metafora dello Stato onnipotente. Anton LaVey usò il nome nella sua fondazione della Chiesa di Satana nel 1966.</p><h4>📜 Storie</h4><p>Nella mitologia ebraica, Dio uccise la femmina di Leviatano per impedire che si riproducesse — se due Leviataní si fossero accoppiati avrebbero distrutto il mondo. La sua carne è riservata al banchetto dei giusti alla fine dei tempi.</p>`},
    {id:8,free:false,nome:'Mammon',emoji:'💰',grado:'Demone dell\'Avarizia — Signore della Ricchezza Corrotta',
    html:`<h4>📖 Chi è</h4><p>Mammon deriva dall'aramaico "mamona" (ricchezza). Gesù lo menziona nel Discorso della Montagna: "Non potete servire Dio e Mammon." Nel Medioevo divenne un demone personificato, simbolo dell'avarizia e della ricchezza che corrompe l'anima.</p><h4>🌟 Attributi</h4><p>Avarizia, ricchezza materiale ossessiva, corruzione per denaro. Peter Binsfeld lo associò al peccato di avarizia. È rappresentato come un essere che cammina curvo, con gli occhi fissi a terra cercando l'oro.</p><h4>🔮 Curiosità</h4><p>John Milton nel Paradiso Perduto lo descrive come il più basso degli angeli anche in cielo, perché aveva gli occhi sempre rivolti verso il suolo a contemplare le ricchezze del pavimento celeste. Fu il primo ad esclamare "arricchiamoci!" dopo la caduta.</p><h4>📜 Storie</h4><p>Nel Medioevo Mammon era invocato (clandestinamente) da mercanti senza scrupoli. Il nome sopravvive nell'inglese "mammon" che indica la bramosia di ricchezza. Karl Marx lo citò come il dio terreno degli Ebrei, in uno dei suoi scritti giovanili più controversi.</p>`},
    {id:9,free:false,nome:'Belial',emoji:'🎪',grado:'Il Senza Valore — Principe dell\'Anarchia',
    html:`<h4>📖 Chi è</h4><p>Belial è uno dei demoni più antichi, il cui nome ebraico significa "senza valore" o "inutile". Appare nell'Antico Testamento come espressione di malvagità totale. Nei Rotoli del Mar Morto è il capo delle forze del Male, opposto all'Angelo della Luce.</p><h4>🌟 Attributi</h4><p>Anarchia, menzogna, corruzione della legge, tentazione sessuale. Nella Lemegeton ha il grado di re e governa 80 legioni. Si manifesta come due angeli che cavalcano carri di fuoco.</p><h4>🔮 Curiosità</h4><p>La comunità di Qumran, gli Esseni, viveva nella convinzione di essere in guerra cosmica contro Belial e i suoi figli. I loro "Rotoli della Guerra" (1QM) descrivono l'apocalittica battaglia finale tra la luce e le tenebre.</p><h4>📜 Storie</h4><p>Milton nel Paradiso Perduto lo ritrae come il più bello e il più eloquente degli angeli caduti, ma anche il più vile: "Nessuna azione vile mancò dell'approvazione di Belial." È il demone che convinge con parole belle a fare cose ignobili.</p>`},
    {id:10,free:false,nome:'Astaroth',emoji:'🦅',grado:'Duca dell\'Inferno — Grande Duca della Tenebra Occidentale',
    html:`<h4>📖 Chi è</h4><p>Astaroth deriva dalla dea fenicia Astarte (Ishtar), divinità dell'amore e della guerra. La sua trasformazione in demone avvenne gradualmente con la demonizzazione delle divinità pagane. Nella Lemegeton è un Grande Duca che governa 40 legioni.</p><h4>🌟 Attributi</h4><p>Conoscenza del passato e del futuro, scienze liberali, segreti. Si manifesta come un angelo brutto che cavalca un drago infernale e regge una vipera in mano. Il suo alito è pestilenziale.</p><h4>🔮 Curiosità</h4><p>I maghi medievali dovevano tenere un anello d'argento sotto il naso durante l'evocazione per sopportare il fetore di Astaroth. Nonostante ciò, era uno dei demoni più evocati per ottenere conoscenza occulta.</p><h4>📜 Storie</h4><p>La trasformazione di Astarte — la grande dea madre del Medio Oriente — in un demone maschio e ripugnante è uno degli episodi più significativi della guerra religiosa tra paganesimo e monoteismo. Ci racconta come i vincitori riscrivano la storia.</p>`},
    {id:11,free:false,nome:'Moloch',emoji:'🔥',grado:'Il Divoratore di Bambini — Dio del Fuoco',
    html:`<h4>📖 Chi è</h4><p>Moloch è la divinità cananea a cui, secondo la Bibbia, venivano sacrificati i bambini passandoli attraverso il fuoco. La natura esatta di questo culto è ancora dibattuta dagli storici. Nella demonologia è diventato simbolo del sacrificio degli innocenti.</p><h4>🌟 Attributi</h4><p>Sacrificio, fanatismo religioso, potere ottenuto tramite il dolore altrui. Nella demonologia è associato al pianto, poiché i tamburi coprivano le urla dei bambini durante i riti.</p><h4>🔮 Curiosità</h4><p>L'archeologia moderna ha messo in dubbio i racconti biblici sui sacrifici di bambini a Moloch. Molti studiosi ritengono si trattasse di un rituale di dedicazione simbolica, non di un sacrificio reale. Ma il mito ha una potenza che supera la storia.</p><h4>📜 Storie</h4><p>Milton nel Paradiso Perduto descrive Moloch come il più feroce dei demoni caduti, che ancora gronda del sangue dei bambini. Allen Ginsberg nel poema "Howl" (1956) usa Moloch come metafora del capitalismo e dell'industria che divora le giovani generazioni.</p>`},
    {id:12,free:false,nome:'Bael',emoji:'🐸',grado:'Primo Re dell\'Inferno — Signore dell\'Invisibilità',
    html:`<h4>📖 Chi è</h4><p>Bael (o Baal) è il primo e più potente dei 72 demoni della Lemegeton. Comanda 66 legioni di demoni. Il suo nome deriva dal semita Baal, "Signore", originariamente un titolo dato alle divinità locali dei Cananei.</p><h4>🌟 Attributi</h4><p>Invisibilità, saggezza, inganno. Si manifesta con tre teste: rospo, uomo e gatto, al centro una testa di ragno. Chi lo evoca ottiene il potere di rendersi invisibile e di parlare con voce rauca ma sapiente.</p><h4>🔮 Curiosità</h4><p>Il profeta Elia sfidò i sacerdoti di Baal sul Monte Carmelo in uno dei duelli religiosi più drammatici della Bibbia. Quattrocentocinquanta sacerdoti di Baal non riuscirono a far scendere il fuoco dal cielo, mentre Elia lo fece con una sola preghiera.</p><h4>📜 Storie</h4><p>I grimori medievali descrivono riti elaboratissimi per evocare Bael in sicurezza. L'operatore doveva essere protetto all'interno di un triangolo magico tracciato con carbone, recitare preghiere specifiche e non fare contatto visivo diretto con le tre teste del demone.</p>`},
    {id:13,free:false,nome:'Pazuzu',emoji:'💨',grado:'Re dei Venti — Demone della Tempesta',
    html:`<h4>📖 Chi è</h4><p>Pazuzu è un demone dell'antica Mesopotamia, re dei venti del sud-ovest, portatori di siccità e carestia. Paradossalmente era anche usato come protettore contro Lamashtu, la demone infanticida. La sua statua veniva portata in casa per difendere i neonati.</p><h4>🌟 Attributi</h4><p>Venti portatori di malattia, siccità, carestia. Ma anche protezione contro demoni femminili. È raffigurato con corpo umano, testa di leone, ali d'aquila, zampe di rapace e coda di scorpione.</p><h4>🔮 Curiosità</h4><p>Pazuzu conobbe la fama mondiale nel 1973 grazie al film "L'Esorcista" di William Friedkin. La statua che lo rappresenta è la stessa che la protagonista raccoglie in Iraq all'inizio del film. Il vero Pazuzu è visibile al Museo del Louvre di Parigi.</p><h4>📜 Storie</h4><p>Nella visione mesopotamica del mondo, i demoni non erano puramente malvagi: avevano funzioni cosmiche. Pazuzu portava malattie ma cacciava anche Lamashtu — dimostrando che anche nell'oscurità esistono gerarchie e regole.</p>`},
    {id:14,free:false,nome:'Andromalio',emoji:'🐍',grado:'Conte dell\'Inferno — Il Recuperatore',
    html:`<h4>📖 Chi è</h4><p>Andromalio è il 72° e ultimo demone della Lemegeton, Conte dell'Inferno che governa 36 legioni. È famoso come demone paradossalmente "utile": riporta indietro ladri e oggetti rubati, punisce chi ha compiuto ingiustizie e rivela dove si trovano i tesori nascosti.</p><h4>🌟 Attributi</h4><p>Giustizia sommaria, recupero dei beni rubati, rivelazione delle frodi. Si manifesta come un uomo che regge un serpente. Era uno dei demoni più praticamente evocati nel Rinascimento.</p><h4>🔮 Curiosità</h4><p>L'uso di Andromalio per recuperare oggetti rubati era così comune che i grimori includevano istruzioni semplificate "per i laici". È uno dei pochi casi in cui la demonologia medievale aveva uno scopo puramente pratico e quotidiano.</p><h4>📜 Storie</h4><p>Un aneddoto del XVIII secolo racconta di un libraio veneziano che evocò Andromalio dopo il furto del suo magazzino. Il giorno dopo, un uomo sconosciuto si presentò con tutti i libri rubati, dichiarandosi "costretto da una forza invisibile" a restituirli. Non fu mai identificato.</p>`},
    {id:15,free:false,nome:'Vepar',emoji:'⚓',grado:'Duca del Mare — Signore delle Acque Oscure',
    html:`<h4>📖 Chi è</h4><p>Vepar è un Grande Duca dell'Inferno che governa 29 legioni di spiriti. Governa le acque e le navi in mare. Si manifesta come sirena armata. Può provocare tempeste, fare infettare le ferite fino alla cancrena e fare morire gli uomini in tre giorni.</p><h4>🌟 Attributi</h4><p>Mare, tempeste, ferite che marciscono, guida delle navi. Paradossalmente è anche uno dei demoni che può essere evocato per guarire: conosce le erbe e i rimedi, ma li usa raramente a fin di bene.</p><h4>🔮 Curiosità</h4><p>La sua apparizione come sirena armata è uno dei più insoliti nella demonologia. Mescola il femminile e il bellico in un'immagine che anticipa certe figure delle mitologie nordiche, come le Valchirie del mare.</p><h4>📜 Storie</h4><p>Marinai medievali che si credevano stregati dai demoni del mare ricorrevano a esorcismi specifici che invocavano Vepar per nome, chiedendogli di rilasciare le navi o i corpi dei compagni. Il mare era il territorio demoniaco per eccellenza nella cosmologia medievale.</p>`},
    {id:16,free:false,nome:'Satana',emoji:'😈',grado:'L\'Avversario — Il Grande Accusatore',
    html:`<h4>📖 Chi è</h4><p>Satana (dall'ebraico "ha-satan", "l'avversario") non è originariamente un nome proprio ma un ruolo: l'accusatore nel tribunale celeste. Nel Libro di Giobbe è un membro del consiglio divino, non un ribelle. Solo con il tempo divenne il signore del Male.</p><h4>🌟 Attributi</h4><p>Tentazione, accusa, dubbio sulla bontà divina, signoria sul mondo materiale. Nel Nuovo Testamento diventa "il principe di questo mondo" e "il padre della menzogna".</p><h4>🔮 Curiosità</h4><p>Nella sua evoluzione storica, Satana assorbe caratteristiche di divinità avversarie: il persiano Angra Mainyu, il cananeo Mot, l'egiziano Set. È un'entità composita formatasi lungo mille anni di sincretismo religioso.</p><h4>📜 Storie</h4><p>Mark Twain scrisse "Lettere dalla Terra", in cui Satana visita la Terra e scrive lettere ironiche agli arcangeli, stupito dell'assurdità degli esseri umani. Dostoevskij nei "Fratelli Karamazov" lo fece comparire come un gentiluomo squallido che ammette candidamente di non credere nell'Inferno.</p>`},
    {id:17,free:false,nome:'Marchosias',emoji:'🐺',grado:'Marchese dell\'Inferno — Il Guerriero',
    html:`<h4>📖 Chi è</h4><p>Marchosias è il 35° demone della Lemegeton, Marchese dell'Inferno con 30 legioni al suo comando. Si manifesta come lupa con ali di grifone e coda di serpente, ma può assumere forma umana se richiesto dall'evocatore.</p><h4>🌟 Attributi</h4><p>Combattimento, lealtà insolita per un demone, risposta alle domande difficili. È considerato uno dei demoni "affidabili" della Lemegeton, nel senso che mantiene i patti senza ingannare chi lo evoca.</p><h4>🔮 Curiosità</h4><p>Marchosias è uno dei pochissimi demoni che si lamenta della propria condizione: secondo la Lemegeton spera ancora di tornare in Paradiso dopo 1.200 anni. I grimori lo presentano quasi con simpatia, come un soldato onorevole in una guerra sbagliata.</p><h4>📜 Storie</h4><p>Nella tradizione degli esorcismi medievali, Marchosias era considerato uno dei demoni più "trattabili". Confessava i peccati nascosti delle persone possedute e indicava i rimedi. Questo aspetto ambiguo — un demone che aiuta — ha affascinato i teologi per secoli.</p>`},
    {id:18,free:false,nome:'Agares',emoji:'🐊',grado:'Duca dell\'Inferno — Maestro delle Lingue',
    html:`<h4>📖 Chi è</h4><p>Agares è il secondo demone della Lemegeton, Duca dell'Inferno che governa 31 legioni. Si manifesta come un vecchio gentile che cavalca un coccodrillo e regge uno sparviero sul pugno. Insegna tutte le lingue del mondo e fa ballare i nemici.</p><h4>🌟 Attributi</h4><p>Lingue e idiomi, viaggio, terremoti, umiliazione dei nemici. Può fermare i fuggitivi, far avanzare i pusillanimi e recuperare i beni perduti. È un demone di grande utilità pratica.</p><h4>🔮 Curiosità</h4><p>L'immagine di un anziano su un coccodrillo con uno sparviero è curiosamente simile alle raffigurazioni egiziane di Sobek, il dio-coccodrillo. Molti studiosi vedono nei demoni della Lemegeton sopravvivenze di antiche divinità mediterranee e medio-orientali.</p><h4>📜 Storie</h4><p>Un grimorio del XVII secolo descrive come invocare Agares per imparare rapidamente una lingua straniera: il rito richiedeva 40 giorni di invocazioni all'alba, un vaso di terracotta con terra presa da tre incroci, e la promessa di non usare la nuova conoscenza a scopo di frode.</p>`},
    {id:19,free:false,nome:'Baphomet',emoji:'🐏',grado:'L\'Idolo dei Templari — Il Capro Sabbatario',
    html:`<h4>📖 Chi è</h4><p>Baphomet è un'entità enigmatica, accusata di essere l'idolo segreto dei Cavalieri Templari al processo del 1307. Il nome ha origini incerte — forse una corruzione di "Maometto" o dal greco "baphe metis" (battesimo di saggezza). La sua iconografia moderna è creazione di Eliphas Lévi nel 1856.</p><h4>🌟 Attributi</h4><p>Dualità, equilibrio tra opposti, conoscenza proibita, androginia sacra. Il Baphomet di Lévi unisce maschile e femminile, bestia e uomo, luce e oscurità — è un simbolo alchemico prima che demoniaco.</p><h4>🔮 Curiosità</h4><p>Storicamente, è molto probabile che i Templari non adorassero affatto Baphomet: le "confessioni" furono estorte sotto tortura da Filippo IV di Francia che voleva impossessarsi dei loro beni. La storia di Baphomet è anzitutto una storia di propaganda politica medievale.</p><h4>📜 Storie</h4><p>La statua moderna di Baphomet del Satanic Temple, installata in Oklahoma nel 2015 accanto ai Dieci Comandamenti, scatenò una tempesta legale e mediatica. Il Satanic Temple la usa come simbolo di separazione tra chiesa e stato, non di culto satanico.</p>`},
    {id:20,free:false,nome:'Abaddon',emoji:'🌑',grado:'Angelo dell\'Abisso — Il Distruttore',
    html:`<h4>📖 Chi è</h4><p>Abaddon appare nell'Apocalisse di Giovanni come "l'angelo del baratro senza fondo", re delle locuste infernali che tormentano l'umanità. Il nome ebraico significa "distruzione" o "abisso". In greco il suo nome è Apollyon, il Distruttore.</p><h4>🌟 Attributi</h4><p>Distruzione, caos escatologico, fine delle cose. È uno dei pochi esseri demoniaci direttamente menzionati nel Nuovo Testamento con nome e titolo. Governa le locuste con teste d'uomo e code di scorpione.</p><h4>🔮 Curiosità</h4><p>Nell'Antico Testamento Abaddon è semplicemente un luogo — il regno dei morti — non un essere. La sua personificazione avviene nell'Apocalisse. Questa evoluzione da "luogo" a "persona" è uno dei processi più affascinanti della mitologia religiosa.</p><h4>📜 Storie</h4><p>John Bunyan nel "Pellegrinaggio del Cristiano" (1678) lo rende uno dei più memorabili antagonisti della letteratura cristiana: un mostro alato che combatte con il protagonista nella Valle dell'Umiliazione, urlando "Ti ho vinto!" mentre il pellegrino cade, ma che viene sconfitto da una preghiera.</p>`},
  ];

  function checkPremium(){
    if(typeof isPremium==='function') return isPremium();
    try{return localStorage.getItem('MYSTICA_PREMIUM_ACTIVE')==='true';}catch(e){return false;}
  }

  function renderList(data,panelId,isDevil){
    const panel=document.getElementById(panelId);
    if(!panel) return;
    const premium=checkPremium();
    panel.innerHTML='';
    data.forEach(item=>{
      const locked=!item.free&&!premium;
      const div=document.createElement('div');
      div.className='angeli-card'+(isDevil?' diavoli-card':'')+(locked?' locked':'');
      div.innerHTML=`<div class="angeli-card-header">
        <span class="angeli-card-icon">${item.emoji}</span>
        <div class="angeli-card-title">${item.nome}<br><small style="font-size:10px;color:var(--muted);font-family:Crimson Pro,serif;font-weight:normal">${item.grado}</small></div>
        <span class="angeli-card-badge ${locked?'locked':''}">${item.free?'✨ Gratuito':(premium?'⭐ Premium':'🔒 Premium')}</span>
      </div>
      <div class="angeli-card-content" id="ac-${isDevil?'d':'a'}-${item.id}">${item.html}</div>`;
      div.addEventListener('click',()=>{
        if(locked){
          if(typeof showPremiumModal==='function') showPremiumModal(()=>{renderList(data,panelId,isDevil);});
          else if(typeof requirePremium==='function') requirePremium(()=>{});
          return;
        }
        const content=document.getElementById(`ac-${isDevil?'d':'a'}-${item.id}`);
        if(!content) return;
        const isOpen=content.classList.contains('open');
        document.querySelectorAll('.angeli-card-content.open').forEach(el=>el.classList.remove('open'));
        if(!isOpen) content.classList.add('open');
      });
      panel.appendChild(div);
    });
  }

  window.MysticaAngeli={
    apri:()=>{
      const sec=document.getElementById('angeli-sezione');
      sec.style.display='block';
      sec.scrollTop=0;
      renderList(ANGELI,'angeli-panel',false);
      renderList(DIAVOLI,'diavoli-panel',true);
    },
    chiudi:()=>{document.getElementById('angeli-sezione').style.display='none';},
    tab:(which)=>{
      document.querySelectorAll('.angeli-tab').forEach(t=>t.classList.remove('active-angeli'));
      document.querySelectorAll('.angeli-panel').forEach(p=>p.classList.remove('active'));
      const idx=which==='angeli'?0:1;
      document.querySelectorAll('.angeli-tab')[idx].classList.add('active-angeli');
      document.getElementById(which+'-panel').classList.add('active');
    }
  };
})();

