(function() {
  const DATA = [
  {id:1,title:"Il Cerchio di Sale",badge:"Protezione",free:true,html:`<h4>📜 Origine Storica</h4><ul><li>Magia popolare europea, alchimia medievale, grimori rinascimentali</li><li>Il sale era considerato "incorruttibile", capace di respingere impurità, malattie e influssi ostili</li></ul><h4>🕯️ Occorrente & Momento</h4><ul><li>Sale grosso naturale, candela bianca, ciotola, abiti chiari</li><li>Luna calante, tramonto, sabato. Evitare temporali o vento forte</li></ul><h4>📐 Procedura</h4><p>Disporre il sale in senso orario partendo da est, senza interruzioni. Accendere la candela e restare immobili 7 minuti. Formula tradizionale: <i>"Nessuna ombra attraversi questo confine."</i></p><h4>🧠 Significato</h4><p>Funziona come tecnica meditativa e delimitazione mentale. Crea un confine psicologico di sicurezza e concentrazione.</p>`},
  {id:2,title:"Purificazione con la Salvia",badge:"Purificazione",free:true,html:`<h4>📜 Origine</h4><p>Tradizioni indigene nordamericane e diffusione esoterica occidentale. Il fumo aveva funzione purificatrice, antisettica e spirituale.</p><h4>🌿 Occorrente & Momento</h4><ul><li>Fascio di salvia bianca, ciotola (terracotta/abalone), piuma o mano</li><li>Alba, dopo litigi, malattie o cambio casa</li></ul><h4>🌬️ Procedura</h4><p>Aprire una finestra. Accendere la salvia, spegnere la fiamma lasciando brace e fumo. Camminare lentamente in senso orario, indirizzando il fumo negli angoli, dietro porte e sotto finestre.</p><h4>🗣️ Formula</h4><p><i>"Che il pesante si dissolva e rimanga solo la pace."</i></p>`},
  {id:3,title:"Formula contro il Malocchio",badge:"Folklore Italiano",free:true,html:`<h4>📜 Origine</h4><p>Folklore del Sud Italia (Campania, Sicilia, Calabria, Puglia). Tramandata oralmente, spesso solo la notte di Natale, da donne anziane.</p><h4>🥣 Occorrente & Giorni</h4><ul><li>Piatto bianco, acqua, olio d'oliva</li><li>Martedì o Venerdì. Mai domenica</li></ul><h4>💧 Procedura</h4><p>Riempire il piatto d'acqua, fare il segno della croce, lasciare cadere tre gocce d'olio. Osservare: se l'olio resta compatto non c'è malocchio, se si disperde indica presenza simbolica di invidia.</p><h4>👥 Aspetto Antropologico</h4><p>Serviva a rassicurare, calmare l'ansia e dare un senso logico a sfortune improvvise.</p>`},
  {id:4,title:"Il Nodo di Iside (Tyet)",badge:"Antico Egitto",free:false,html:`<h4>📜 Origine</h4><p>Antico Egitto. Associato alla dea Iside. Il Tyet era chiamato "Nodo del Sangue" o "Nodo della Vita".</p><h4>🔮 Occorrente & Momento</h4><ul><li>Pietra rossa, diaspro, corniola, lino rosso</li><li>Viaggi, gravidanza, malattia, riti funerari</li></ul><h4>📐 Procedura</h4><p>L'amuleto veniva lavato con acqua profumata, esposto al sole nascente e legato vicino al petto.</p><h4>🗣️ Formula & Simbolismo</h4><p>Versioni derivate dal <i>Book of the Dead</i> invocavano protezione divina. Il rosso simboleggiava vita, sangue ed energia difensiva.</p>`},
  {id:5,title:"Il Ferro di Cavallo",badge:"Europa Medievale",free:false,html:`<h4>📜 Origine</h4><p>Europa medievale. Il ferro era considerato repellente per streghe, spiriti e fate ostili.</p><h4>🛡️ Occorrente & Posizione</h4><ul><li>Ferro di cavallo usato, chiodi in ferro</li><li>Punte verso l'alto, sopra la porta principale</li><li>Sabato mattina</li></ul><h4>📐 Procedura</h4><p>Alcuni aggiungevano 7 chiodi o un ramo d'ulivo vicino. Tradizionalmente fissato con intenzione di protezione.</p><h4>👥 Significato</h4><p>Protezione domestica e prosperità. Il gesto materializzava il confine tra interno sicuro ed esterno incerto.</p>`},
  {id:6,title:"Esorcismo dell'Acqua e del Sale",badge:"Tardo Medioevo",free:false,html:`<h4>📜 Origine</h4><p>Tardo medioevo cristiano, diffuso in monasteri e rituali popolari.</p><h4>💧 Occorrente & Momento</h4><ul><li>Sale, acqua sorgiva, ciotola d'argento/ceramica, candela</li><li>Dopo lutti, malattie, litigi, incubi frequenti</li></ul><h4>📐 Procedura</h4><p>Il sale veniva versato nell'acqua pronunciando formule latine. Si aspergevano muri, porte, finestre e letto.</p><h4>👥 Simbolismo</h4><p>L'acqua purifica, il sale conserva e protegge. Rito di pulizia simbolica post-trauma.</p>`},
  {id:7,title:"Bagno di Purificazione all'Issoppo",badge:"Tradizione Biblica",free:false,html:`<h4>📜 Origine</h4><p>Tradizioni bibliche e mediterranee. L'issoppo compare nei testi sacri come pianta purificatrice.</p><h4>🌿 Occorrente & Procedura</h4><ul><li>Issoppo essiccato, sale marino, acqua calda, candela bianca</li><li>Lasciare in infusione, versare nell'acqua del bagno, restare immersi 15 min</li></ul><h4>⚠️ Regola Antica</h4><p>Non parlare durante il bagno. "Lavare via" il peso emotivo.</p>`},
  {id:8,title:"Il Quadrato del Sator",badge:"Antica Roma",free:false,html:`<h4>📜 Origine</h4><p>Antica Roma. Trovato su muri, amuleti, caserme e monasteri. Palindromo famoso.</p><h4>📝 Il Quadrato</h4><p style="text-align:center;font-family:monospace;background:rgba(0,0,0,0.3);padding:10px;border-radius:8px;margin:8px 0;">SATOR<br>AREPO<br>TENET<br>OPERA<br>ROTAS</p><h4>🛡️ Uso Tradizionale</h4><p>Scritto su carta, pergamena o legno. Portato durante viaggi, battaglie, traversate. Proteggeva da incendi, incidenti, malattie.</p>`},
  {id:9,title:"Sigillo di Salomone",badge:"Magia Cerimoniale",free:false,html:`<h4>📜 Origine</h4><p>Magia cerimoniale medievale. Associato alla <i>Key of Solomon</i>.</p><h4>🖋️ Materiali & Preparazione</h4><ul><li>Pergamena vergine, inchiostro nero, candela blu, incenso</li><li>Praticante digiunava leggermente, evitava rumori, lavorava in silenzio</li></ul><h4>📐 Procedura</h4><p>Il simbolo tracciato lentamente. Ogni linea: equilibrio, dominio della mente, ordine sul caos. Rivolti verso est.</p><h4>🧠 Scopo</h4><p>Protezione mentale e disciplina spirituale.</p>`},
  {id:10,title:"L'Amuleto dell'Aglio",badge:"Folklore Europeo",free:false,html:`<h4>📜 Origine</h4><p>Folklore europeo e mediterraneo. Considerato antisettico, protettivo, scaccia-spiriti.</p><h4>🧄 Occorrente & Posizione</h4><ul><li>Tre teste d'aglio, spago naturale rosso</li><li>Cucina, porta d'ingresso, finestra</li></ul><h4>📅 Momento & Curiosità</h4><p>Luna nuova o raccolto estivo. Nel folklore proteggeva da vampiri, peste e "malocchio".</p><h4>👥 Significato</h4><p>Strumento psicologico e sociale per creare ordine mentale e senso di protezione.</p>`},
  {id:11,title:"Il Barattolo del Denaro",badge:"Prosperità",free:false,html:`<h4>📜 Origine</h4><p>Magia popolare europea, hoodoo americano, tradizioni contadine. Simbolo di ricchezza e sicurezza invernale.</p><h4>🪙 Occorrente & Momento</h4><ul><li>Barattolo vetro, monete, cannella, alloro, zucchero, calamita, candela verde</li><li>Luna crescente, giovedì, prime ore della sera</li></ul><h4>📐 Procedura</h4><p>Inserire lentamente gli oggetti. Formula: <i>"Che ciò che mi serve trovi la strada verso di me."</i></p><h4>📍 Dove Tenerlo</h4><p>Vicino all'ingresso, lavoro o documenti. Mai a terra. Focalizza obiettivi e riduce paura economica.</p>`},
  {id:12,title:"Incantesimo del Nodo della Fortuna",badge:"Destino Favorevole",free:false,html:`<h4>📜 Origine</h4><p>Tradizioni celtiche, magia marinaresca, folklore nordico. Il nodo fissa un'intenzione e sigilla una promessa.</p><h4>🪢 Procedura</h4><p>3 nodi lenti su nastro verde/dorato: 1° opportunità, 2° stabilità, 3° successo. Visualizzare la scena positiva a ogni nodo.</p><h4>🗣️ Formula</h4><p><i>"Con il primo nodo apro la via. Con il secondo la fortuna resta. Con il terzo il cammino si compie."</i></p><h4>📦 Conservazione</h4><p>Portafoglio, tasca, sotto cuscino o agenda. Aiuta concentrazione e senso di controllo.</p>`},
  {id:13,title:"Formula dell'Alloro sotto il Cuscino",badge:"Sogni & Intuizione",free:false,html:`<h4>📜 Origine</h4><p>Tradizione romana e greca. Alloro sacro ad Apollo: profezia, lucidità, vittoria.</p><h4>🌿 Occorrente & Momento</h4><ul><li>3 foglie secche, sacchetto bianco, candela blu/bianca</li><li>Prima della mezzanotte, luna piena, notte dom/lun</li></ul><h4>📐 Procedura</h4><p>Scrivere domanda, mettere foglio e foglie sotto cuscino. Spegnere candela senza soffiare. Interpretare i sogni al risveglio.</p><h4>🧠 Significato</h4><p>Stimola introspezione, attenzione ai sogni ed elaborazione subconscia.</p>`},
  {id:14,title:"Consacrazione della Moneta",badge:"Prosperità Personale",free:false,html:`<h4>📜 Origine</h4><p>Europa medievale, tradizioni romane, folklore mercantile. Usata da mercanti, soldati, viaggiatori.</p><h4>🪙 Occorrente & Procedura</h4><ul><li>Moneta lucida, acqua corrente, sale, panno bianco, candela verde</li><li>Lavare, passare nel sale, asciugare, tenere tra le mani</li></ul><h4>🗣️ Formula & Curiosità</h4><p><i>"Come questa moneta resta con me, così resti la buona sorte."</i> Alcuni marinai la cucivano nei vestiti.</p><h4>📍 Dove</h4><p>Portafoglio o tasca destra. Mai regalarla. Ancora mentale di sicurezza economica.</p>`},
  {id:15,title:"Rituale del Grano e del Riso",badge:"Benedizione Raccolto",free:false,html:`<h4>📜 Origine</h4><p>Rituale agricolo europeo antichissimo. Grano = vita, riso = fertilità e abbondanza.</p><h4>🌾 Occorrente & Procedura</h4><ul><li>Chicchi di grano, riso bianco, candela dorata</li><li>Spargere su soglia, cucina, ingresso</li></ul><h4>🗣️ Formula</h4><p><i>"Che questa casa non conosca fame né mancanza."</i></p><h4>👥 Variante Matrimoniale & Significato</h4><p>Lanciato sugli sposi per prosperità. Rafforza comunità ed esorcizza paura della carestia.</p>`},
  {id:16,title:"Incantesimo della Candela Verde",badge:"Crescita & Denaro",free:false,html:`<h4>📜 Origine</h4><p>Esoterismo medievale, magia popolare, tradizione ermetica. Verde = crescita, denaro, sviluppo.</p><h4>🕯️ Occorrente & Preparazione</h4><ul><li>Candela verde, cannella, foglio obiettivo, olio d'oliva/basilico</li><li>Strofinare dal basso verso l'alto con olio</li></ul><h4>📐 Procedura</h4><p>Accendere lentamente. Lasciar consumare fino a metà. Formula: <i>"Come cresce questa luce, così cresca il mio cammino."</i></p><h4>🔍 Interpretazione</h4><p>Fiamma stabile = buon auspicio. Focalizza attenzione e rafforza motivazione.</p>`},
  {id:17,title:"Invocazione di Abundantia",badge:"Dea della Ricchezza",free:false,html:`<h4>📜 Origine</h4><p>Figura romana associata a prosperità, raccolto, fortuna domestica. Cornucopia, monete, grano.</p><h4>🍷 Occorrente & Momento</h4><ul><li>Pane, vino, candela dorata, ciotola</li><li>Tramonto, fine settimana, inizio attività economica</li></ul><h4>📐 Procedura</h4><p>Accendere candela, versare vino, spezzare pane lentamente. Restare in contemplazione.</p><h4>🗣️ Formula & Significato</h4><p><i>"Che il necessario non manchi mai a questa casa."</i> Si chiede stabilità e serenità, non lusso.</p>`},
  {id:18,title:"La Pietra Calamita (Lodestone)",badge:"Attrazione",free:false,html:`<h4>📜 Origine</h4><p>Hoodoo americano, alchimia, magia commerciale XIX sec. Magnetite naturale.</p><h4>🪨 Occorrente & Procedura</h4><ul><li>Pietra calamita, limatura ferro, panno verde, moneta</li><li>Pulire, avvolgere, "nutrire" con limatura</li></ul><h4>🗣️ Formula & Conservazione</h4><p><i>"Come il ferro segue la pietra, così venga verso di me ciò che cerco."</i> Tenuta in cassetta denaro o tasca interna.</p><h4>🧠 Significato</h4><p>Oggetto motivazionale, simbolo di fiducia e ancora mentale positiva.</p>`},
  {id:19,title:"Rituale del Sale della Terra",badge:"Patrimonio Familiare",free:false,html:`<h4>📜 Origine</h4><p>Tradizione rurale europea. Terra = stabilità, eredità, continuità.</p><h4>🌍 Occorrente & Procedura</h4><ul><li>4 monete, sale grosso, piccola pala, candela bianca</li><li>Seppellire monete ai 4 angoli proprietà con pizzico di sale</li></ul><h4>🗣️ Formula</h4><p><i>"Che questa terra resti salda, fertile e protetta."</i></p><h4>👥 Significato</h4><p>Rafforza legame con la casa ed esorcizza paura della perdita.</p>`},
  {id:20,title:"Fumigazione di Benzoino",badge:"Apertura Strade",free:false,html:`<h4>📜 Origine</h4><p>Templi orientali, monasteri, magia popolare. Resina purificante e calmante.</p><h4>💨 Occorrente & Procedura</h4><ul><li>Resina benzoino, carboncino, braciere, candela dorata</li><li>Accendere carbone, posare resina, camminare in senso orario</li></ul><h4>🗣️ Formula</h4><p><i>"Che le vie chiuse si aprano e ciò che è fermo torni a muoversi."</i></p><h4>🧠 Effetto</h4><p>L'aroma rilassa, migliora concentrazione e crea atmosfera rituale.</p>`},
  {id:21,title:"Sacchetto di Venere",badge:"Amore & Attrazione",free:false,html:`<h4>📜 Origine</h4><p>Convergenza tra filtri medievali e mojo bag afroamericani. Archetipo di oggetto-caricatore.</p><h4>🌹 Materiali & Procedura</h4><ul><li>Lino/cotone, petali rosa, lavanda, quarzo rosa (moderno)</li><li>Inserire elementi con attenzione tattile, soffiare dentro, chiudere</li></ul><h4>📅 Tempistica & Funzione</h4><p>Venerdì, luna crescente. Dispositivo di focalizzazione cognitiva e affettiva per stabilizzare intenzione emotiva.</p>`},
  {id:22,title:"Specchio dell'Autostima",badge:"Mirror Work",free:false,html:`<h4>📜 Origine</h4><p>Matrici ascetiche, tecniche di confessione, psicologia del sé (XX sec).</p><h4>🪞 Procedura</h4><ul><li>Posizionarsi frontalmente, contatto visivo prolungato</li><li>Pronunciare frasi in presente ("sono", "accetto"), mantenere sguardo</li></ul><h4>📅 Tempistica & Funzione</h4><p>Mattino. Tecnica di riallineamento dell'identità narrativa tramite feedback visivo diretto.</p>`},
  {id:23,title:"Legame del Nastro Rosso",badge:"Unione & Destino",free:false,html:`<h4>📜 Origine</h4><p>Tradizione cinese (filo destino), folklore europeo, reinterpretazioni neopagane.</p><h4>🎗️ Procedura</h4><p>Avvolgere nastro attorno a 2 oggetti simbolici con movimenti circolari. Ogni giro = qualità (fedeltà, continuità). Chiudere con nodo.</p><h4>📅 Tempistica & Funzione</h4><p>Luna crescente/plenilunio. Materializzazione del legame sociale: marcatore fisico di relazione.</p>`},
  {id:24,title:"Bagno ai Petali di Calendula",badge:"Transizione Emotiva",free:false,html:`<h4>📜 Origine</h4><p>Erboristeria medievale europea (monasteri benedettini, scuola salernitana).</p><h4>🌼 Procedura</h4><p>Infusione petali in acqua calda. Immersione o lavaggio mani/viso. Accompagnare da introspezione.</p><h4>📅 Tempistica & Funzione</h4><p>Sera o momenti di transizione. Rito liminale per segnare passaggio tra stati emotivi.</p>`},
  {id:25,title:"Candela Rosa per l'Armonia",badge:"Relazioni Pacificate",free:false,html:`<h4>📜 Origine</h4><p>Magia cerimoniale moderna, sistema ermetico colore-pianeta-emozione.</p><h4>🕯️ Procedura</h4><p>Accendere in ambiente stabile. Osservare fiamma, visualizzare relazioni pacificate. Spegnere senza soffiare.</p><h4>🧠 Funzione</h4><p>Tecnica di regolazione emotiva tramite attenzione focalizzata e simbolismo cromatico.</p>`},
  {id:26,title:"Melissa e Miele",badge:"Calma & Sollievo",free:false,html:`<h4>📜 Origine</h4><p>Dioscoride, medicina monastica medievale. Melissa officinalis = erba calmante.</p><h4>☕ Procedura</h4><p>Infuso caldo + miele. Consumo lento in quiete.</p><h4>📅 Tempistica & Funzione</h4><p>Sera o stress. Rituale farmacologico simbolico: sedazione lieve reale + effetto percepito potenziato dal gesto.</p>`},
  {id:27,title:"Nodo d'Amore",badge:"Unione Celtica/Marina",free:false,html:`<h4>📜 Origine</h4><p>Tradizioni celtiche, folklore marinaro, manoscritti medievali.</p><h4>🪢 Procedura</h4><p>Intrecciare filo lentamente. Ogni nodo = valore relazionale. Nodo finale sigilla l'intenzione.</p><h4>🧠 Funzione</h4><p>Metafora fisica della coesione sociale e affettiva.</p>`},
  {id:28,title:"Rilascio del Passato",badge:"Combustione Simbolica",free:false,html:`<h4>📜 Origine</h4><p>Tabellae greco-romane, rituali medievali, spiritismo moderno.</p><h4>🔥 Procedura</h4><p>Scrivere contenuto emotivo, leggere, bruciare in contenitore sicuro, disperdere ceneri.</p><h4>📅 Tempistica & Funzione</h4><p>Notte o chiusura emotiva. Atto di esternalizzazione cognitiva del trauma.</p>`},
  {id:29,title:"Amuleto di Giada",badge:"Armonia & Equilibrio",free:false,html:`<h4>📜 Origine</h4><p>Cina preimperiale, tradizione confuciana/taoista.</p><h4>🪨 Procedura</h4><p>Portare a contatto col corpo, "purificare" con acqua/fumo, stabilizzare come oggetto personale.</p><h4>🧠 Funzione</h4><p>Oggetto di stabilizzazione identitaria e sociale, non talismano operativo.</p>`},
  {id:30,title:"Invocazione di Erzulie",badge:"Vodou & Archetipo",free:false,html:`<h4>📜 Origine</h4><p>Lwa del Vodou haitiano, sincretizzata con figure mariane.</p><h4>🌸 Procedura</h4><p>Preparare altare domestico, invocazione cantata/recitata, offerta simbolica, momento di contemplazione.</p><h4>📅 Tempistica & Funzione</h4><p>Cerimonie o crisi emotiva. Mediazione sociale/psicologica tramite archetipi femminili.</p>`},
  {id:31,title:"Artemisia per i Sogni",badge:"Sogno & Memoria",free:false,html:`<h4>📜 Origine</h4><p>Fitoterapia europea antica. Artemisia vulgaris associata a luna e dimensione notturna.</p><h4>🌿 Procedura</h4><p>Tisana leggera o sacchetto cuscino. Momento di quiete pre-sonno. Ripetere intenzione di ricordare.</p><h4>🧠 Funzione</h4><p>Dispositivo di induzione attentiva al sogno tramite autosuggestione e ritualizzazione del sonno.</p>`},
  {id:32,title:"Consacrazione dei Tarocchi",badge:"Attivazione Simbolica",free:false,html:`<h4>📜 Origine</h4><p>Rinterpretazione esoterica XVIII-XIX sec (Lévi, società ermetiche).</p><h4>🃏 Procedura</h4><p>Tenere mazzo, esporre a fumo incenso, passare carte singolarmente (opz.). Utilizzo esclusivo.</p><h4>📅 Tempistica & Funzione</h4><p>Inizio utilizzo, luna crescente. Ritualizzazione della relazione soggetto-sistema simbolico.</p>`},
  {id:33,title:"Meditazione della Candela Bianca",badge:"Attenzione & Purezza",free:false,html:`<h4>📜 Origine</h4><p>Contemplazione occidentale/orientale (dharana yogica, luce cristiana).</p><h4>🕯️ Procedura</h4><p>Accendere, fissare fiamma senza sforzo, ridurre dialogo interno, ritornare a ogni distrazione.</p><h4>📅 Tempistica & Funzione</h4><p>10-20 min serali. Regolazione attentiva e riduzione rumore cognitivo.</p>`},
  {id:34,title:"Rituale della Luna Piena",badge:"Sincronizzazione Ciclica",free:false,html:`<h4>📜 Origine</h4><p>Culture agricole pre-moderne. Riferimento naturale per raccolta/fertilità.</p><h4>🌕 Procedura</h4><p>Disporre oggetti personali sotto luce lunare, osservare in silenzio, formulare intenzioni.</p><h4>📅 Tempistica & Funzione</h4><p>Notte plenilunio. Sincronizzazione simbolica con cicli naturali ordinatori.</p>`},
  {id:35,title:"Incenso d'Olibano",badge:"Sacralità Antica",free:false,html:`<h4>📜 Origine</h4><p>Egitto, Grecia, Roma, liturgie cristiane. Associato a purificazione.</p><h4>🌬️ Procedura</h4><p>Resina su carbone, diffondere fumo, concentrare su respiro e odore.</p><h4>🧠 Funzione</h4><p>Modulatore sensoriale per stati di attenzione ridotta e introspezione.</p>`},
  {id:36,title:"Bagno di Sale Marino",badge:"Decontaminazione Simbolica",free:false,html:`<h4>📜 Origine</h4><p>Universale: conservazione, purificazione, protezione.</p><h4>🛁 Procedura</h4><p>Sciogliere sale, immersione, quiete senza stimoli, uscita lenta.</p><h4>📅 Tempistica & Funzione</h4><p>Dopo giornate intense. Decontaminazione simbolica di stress e fatica.</p>`},
  {id:37,title:"Incantesimo del Silenzio",badge:"Disciplina Attentiva",free:false,html:`<h4>📜 Origine</h4><p>Monachesimo, ascetismo, pratiche sciamaniche.</p><h4>🤫 Procedura</h4><p>Astensione verbale totale, riduzione stimoli, osservazione pensieri non verbalizzati.</p><h4>📅 Tempistica & Funzione</h4><p>30 min - ore. Deprivazione sensoriale linguistica per consapevolezza introspettiva.</p>`},
  {id:38,title:"Connessione con gli Antenati",badge:"Memoria Generazionale",free:false,html:`<h4>📜 Origine</h4><p>Culti romani (lares), tradizioni africane, memorie familiari.</p><h4>🕯️ Procedura</h4><p>Accendere luce, momento ricordo/narrazione, offerta simbolica, chiusura ringraziamento.</p><h4>📅 Tempistica & Funzione</h4><p>Notte o ricorrenze. Sistema di continuità identitaria tra generazioni.</p>`},
  {id:39,title:"Scrittura Automatica Focalizzata",badge:"Flusso Inconscio",free:false,html:`<h4>📜 Origine</h4><p>Spiritismo ottocentesco (Kardec), scrittura surrealista.</p><h4>📝 Procedura</h4><p>Scrivere senza pianificazione, ridurre controllo cosciente, flusso continuo, lettura successiva.</p><h4>📅 Tempistica & Funzione</h4><p>10-20 min. Accesso facilitato a contenuti cognitivi non filtrati.</p>`},
  {id:40,title:"Consacrazione dello Spazio Sacro",badge:"Delimitazione Rituale",free:false,html:`<h4>📜 Origine</h4><p>Tempulum romano, mandala, cerchi magici medievali.</p><h4>🕯️ Procedura</h4><p>Pulizia area, definizione confini simbolici, oggetti significativi, uso esclusivo.</p><h4>📅 Tempistica & Funzione</h4><p>Inizio nuove pratiche. Segmentazione spazio funzionale per concentrazione.</p>`},
  {id:41,title:"Occhio di Tigre",badge:"Concentrazione",free:false,html:`<h4>📜 Origine</h4><p>Sincretismo mineralogico ottocentesco, occultismo, new age.</p><h4>🪨 Procedura</h4><p>Tenere in mano prima attività impegnativa, "riscaldare" nel palmo, usare ripetutamente.</p><h4>🧠 Funzione</h4><p>Ancoraggio attentivo: correlazione stabile tra stimolo tattile e sicurezza psicologica.</p>`},
  {id:42,title:"Candela Gialla",badge:"Chiarezza Cognitiva",free:false,html:`<h4>📜 Origine</h4><p>Occultismo moderno, ermetismo XIX-XX sec. Colore → stato psicologico.</p><h4>🕯️ Procedura</h4><p>Accendere, focalizzare su fiamma, associare luce a chiarezza, spegnere controllato.</p><h4>🧠 Funzione</h4><p>Priming cognitivo visivo per attività analitiche.</p>`},
  {id:43,title:"Rosmarino sulle Tempie",badge:"Memoria & Lucidità",free:false,html:`<h4>📜 Origine</h4><p>Medicina mediterranea, Grecia/Roma. Simbolo di memoria.</p><h4>🌿 Procedura</h4><p>Applicazione lieve tempie o inalazione aroma. Respirazione lenta.</p><h4>📅 Tempistica & Funzione</h4><p>Prima studio/mnemotecniche. Stimolazione olfattiva per potenziamento attentivo.</p>`},
  {id:44,title:"Ancoraggio del Coraggio",badge:"Risposta Somatica",free:false,html:`<h4>📜 Origine</h4><p>Memoria emotiva sciamanica, formalizzata in psicologia (NLP).</p><h4>💪 Procedura</h4><p>Richiamare ricordo sicurezza, associare a gesto fisico (pugno), ripetere per stabilizzare.</p><h4>🧠 Funzione</h4><p>Condizionamento somatico intenzionale per attivazione in situazioni difficili.</p>`},
  {id:45,title:"Taglio dei Rami Secchi",badge:"Rimozione Ostacoli",free:false,html:`<h4>📜 Origine</h4><p>Simbolismo agricolo, meditazioni guidate moderne.</p><h4>🌳 Procedura</h4><p>Visualizzare problemi come "rami secchi", simulare potatura, percepire alleggerimento.</p><h4>🧠 Funzione</h4><p>Metafora operativa di ristrutturazione cognitiva.</p>`},
  {id:46,title:"Fumigazione di Menta Piperita",badge:"Attivazione Mentale",free:false,html:`<h4>📜 Origine</h4><p>Erboristeria mediterranea/araba. Pianta rinfrescante/stimolante.</p><h4>🍃 Procedura</h4><p>Bruciatura leggera o diffusione aroma, inalazione consapevole.</p><h4>📅 Tempistica & Funzione</h4><p>Mattino/stanchezza. Attivazione fisiologica lieve tramite olfatto.</p>`},
  {id:47,title:"Radice di Zenzero",badge:"Azione & Decisione",free:false,html:`<h4>📜 Origine</h4><p>Ayurveda, medicina cinese. Tonico riscaldante.</p><h4>🌱 Procedura</h4><p>Portare con sé, masticare/annusare, associare a intenzioni di movimento.</p><h4>🧠 Funzione</h4><p>Simbolo somatico di attivazione metabolica e mentale.</p>`},
  {id:48,title:"Terra sotto i Piedi",badge:"Earthing Rituale",free:false,html:`<h4>📜 Origine</h4><p>Culture agrarie, rituali sciamanici, reinterpretazione moderna.</p><h4>👣 Procedura</h4><p>Camminata scalza su suolo naturale, attenzione contatto, respirazione lenta.</p><h4>🧠 Funzione</h4><p>Riconnessione sensoriale con ambiente naturale.</p>`},
  {id:49,title:"Scudo Mentale Visivo",badge:"Protezione Ansia",free:false,html:`<h4>📜 Origine</h4><p>Immaginazione sciamanica, meditazioni moderne.</p><h4>🛡️ Procedura</h4><p>Visualizzare barriera luminosa, definire confini, rafforzare con respiro, richiamare in stress.</p><h4>🧠 Funzione</h4><p>Regolazione ansia tramite imagery protettiva.</p>`},
  {id:50,title:"Consacrazione della Penna",badge:"Successo Strumentale",free:false,html:`<h4>📜 Origine</h4><p>Benedizione strumenti in mestieri/religioni.</p><h4>🖋️ Procedura</h4><p>Passare vicino a fuoco/luce, associare a successo, uso esclusivo per attività importanti.</p><h4>🧠 Funzione</h4><p>Sacralizzazione funzionale che aumenta valore percepito dello strumento.</p>`},
  {id:51,title:"Sale nei Quattro Angoli",badge:"Stabilità Spaziale",free:false,html:`<h4>📜 Origine</h4><p>Grecia/Roma, tradizione ebraica, folklore medievale. Spazio come area ordinabile.</p><h4>🧂 Procedura</h4><p>Deporre sale nei 4 punti estremi stanza/casa in silenzio con intenzione di stabilizzazione.</p><h4>📅 Tempistica & Funzione</h4><p>Inizio ciclo/cambiamento. Marcatura simbolica per ristabilire ordine percepito.</p>`},
  {id:52,title:"Campanello d'Ottone",badge:"Rottura Stagnazione",free:false,html:`<h4>📜 Origine</h4><p>Campane tibetane, Europa medievale, sciamanesimo. Dispositivo di interruzione percettiva.</p><h4>🔔 Procedura</h4><p>Suonare in ogni stanza lentamente, lasciare decadere suono, respirazione lenta.</p><h4>📅 Tempistica & Funzione</h4><p>Dopo conflitti/stagnazione. Discontinuità acustica per riorganizzazione cognitiva.</p>`},
  {id:53,title:"Lavanda sugli Stipiti",badge:"Soglia di Pace",free:false,html:`<h4>📜 Origine</h4><p>Erboristeria romana/mediterranea (lavare → purificare).</p><h4>🌸 Procedura</h4><p>Applicare olio/rametti su stipiti, movimento interno/esterno, associazione "entrata di pace".</p><h4>📅 Tempistica & Funzione</h4><p>Primavera/cambiamenti. Pratica di soglia tra interno sicuro ed esterno incerto.</p>`},
  {id:54,title:"Piantumazione Rituale",badge:"Crescita Intenzionale",free:false,html:`<h4>📜 Origine</h4><p>Mesopotamia, Mediterraneo, Americhe precolombiane. Trasposizione intenzionale agricola.</p><h4>🌱 Procedura</h4><p>Tenere seme con intenzione, piantare lento, irrigare, osservare crescita come metafora.</p><h4>📅 Tempistica & Funzione</h4><p>Primavera/inizio progetti. Metafora operativa di cambiamento graduale.</p>`},
  {id:55,title:"Benedizione del Focolare",badge:"Coesione Domestica",free:false,html:`<h4>📜 Origine</h4><p>Celtiche, romane, contadine europee. Centro simbolico sopravvivenza.</p><h4>🔥 Procedura</h4><p>Accendere/osservare fuoco, silenzio/ringraziamento, gesto protezione, chiusura.</p><h4>📅 Tempistica & Funzione</h4><p>Inverno/riunioni. Rito di coesione sociale e stabilità domestica.</p>`},
  {id:56,title:"Acqua di Sole",badge:"Carica Naturale",free:false,html:`<h4>📜 Origine</h4><p>Pratica rurale diffusa. Esposizione simbolica alla luce.</p><h4>💧 Procedura</h4><p>Esposizione contenitore trasparente per ore, uso per irrigazione/lavaggi, intenzione mentale.</p><h4>📅 Tempistica & Funzione</h4><p>Giorni soleggiati. Trasformazione simbolica tramite ciclo luce/tempo.</p>`},
  {id:57,title:"Pietra Forata",badge:"Visione & Soglia",free:false,html:`<h4>📜 Origine</h4><p>Europa settentrionale/mediterranea. Hag Stone / Odin Stone.</p><h4>🕳️ Procedura</h4><p>Raccogliere in natura, pulire, appendere a porte/finestre, guardare attraverso foro.</p><h4>📅 Tempistica & Funzione</h4><p>Installazione permanente. Oggetto liminale tra visibile e invisibile.</p>`},
  {id:58,title:"Fumigazione di Pino e Abete",badge:"Sanificazione Simbolica",free:false,html:`<h4>📜 Origine</h4><p>Nordiche, alpine. Purificazione ambientale e medica.</p><h4>🌲 Procedura</h4><p>Bruciare aghi lentamente, diffondere fumo in angoli stanza.</p><h4>📅 Tempistica & Funzione</h4><p>Dopo malattie/isolamento. Sanificazione simbolica dell'ambiente.</p>`},
  {id:59,title:"Benvenuto agli Uccelli",badge:"Reciprocità Ecologica",free:false,html:`<h4>📜 Origine</h4><p>Asia, Europa rurale, culture animiste. Gesto di reciprocità naturale.</p><h4>🕊️ Procedura</h4><p>Deposizione cibo su davanzale, osservazione senza interferenza, ripetizione.</p><h4>📅 Tempistica & Funzione</h4><p>Mattino/stagioni fredde. Atto di reciprocità simbolica uomo-ambiente.</p>`},
  {id:60,title:"Congedo delle Energie",badge:"Chiusura Rituale",free:false,html:`<h4>📜 Origine</h4><p>Formula chiusura sistemi medievali/neopagani. "De-attivazione" rito.</p><h4>🚪 Procedura</h4><p>Silenzio, dichiarazione verbale: <i>"Chiuso ciò che è stato aperto, senza danno e senza legame"</i>, riorientamento quotidiano.</p><h4>📅 Tempistica & Funzione</h4><p>Fine pratica. Reintegrazione cognitiva nella normalità, evita discontinuità percettive.</p>`}
  ];

  function checkPremium() {
  if (typeof isPremium === 'function') return isPremium();
  try { return localStorage.getItem('MYSTICA_PREMIUM_ACTIVE') === 'true'; } catch(e) { return false; }
  }

  const container = document.getElementById('rituali-container');
  const modal = document.getElementById('rituali-premium-modal');

  function render() {
  if(!container) return;
  const premium = checkPremium();
  container.innerHTML = '';
  DATA.forEach(r => {
  const isLocked = !r.free && !premium;
  const card = document.createElement('div');
  card.className = `rituale-card ${isLocked ? 'locked' : ''}`;
  card.innerHTML = `
  <div class="rituale-card-header">
  <h3 class="rituale-card-title">${r.id}. ${r.title}</h3>
  <span class="rituale-badge ${r.free ? '' : 'locked'}">${r.free ? '✨ Gratuito' : (premium ? '⭐ Premium' : '🔒 Premium')}</span>
  </div>
  <div class="rituale-content" id="rc-${r.id}">${r.html}</div>
  `;
  card.addEventListener('click', () => toggleCard(card, r.id, isLocked));
  container.appendChild(card);
  });
  }

  function openContent(id) {
  const content = document.getElementById(`rc-${id}`);
  if (!content) return;
  const isOpen = content.classList.contains('open');

  document.querySelectorAll('.rituale-content.open').forEach(el => el.classList.remove('open'));
  if (!isOpen) content.classList.add('open');
  }

  function toggleCard(card, id, isLocked) {

  const locked = !DATA.find(r=>r.id===id)?.free && !checkPremium();
  if (locked) {

  if (typeof showPremiumModal === 'function') {
  showPremiumModal(() => {

  render();
  setTimeout(() => openContent(id), 100);
  });
  } else {
  modal.style.display = 'flex';
  }
  return;
  }

  if (typeof showAdGate === 'function') {
  showAdGate('60 Magie della Tradizione', () => openContent(id));
  } else {
  openContent(id);
  }
  }

  window.MysticaRituali = {
  apri: () => {
  const sec = document.getElementById('rituali-tradizione');
  sec.style.display = 'block';
  sec.scrollTop = 0;
  render();
  },
  chiudi: () => {
  document.getElementById('rituali-tradizione').style.display = 'none';
  },
  chiudiModale: () => { modal.style.display = 'none'; }
  };

  document.addEventListener('DOMContentLoaded', () => {
  const _origUpdatePremiumUI = window.updatePremiumUI;
  if (typeof _origUpdatePremiumUI === 'function') {
  window.updatePremiumUI = function() {
  _origUpdatePremiumUI.apply(this, arguments);
  const sec = document.getElementById('rituali-tradizione');
  if (sec && sec.style.display !== 'none') render();
  };
  }
  });
})();
